In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
l = 12

In [13]:
def fitness(v, target):
    return np.abs(v - target).sum()

def geneneration(n):
    return np.random.randint(low=0, high=1+1, size=(n, l))

def selection(P, target):
    prob = np.array([fitness(p, target) for p in P])
    print(prob)
    select = np.random.choice(len(P), p=prob/prob.sum())
    return select

def mutation(P, n, pm):
    for i in range(n):
        idx = np.random.randint(low=0, high=l)
        if np.random.rand() < pm:
            v = np.random.randint(low=0, high=1+1)
            if P[i, idx] != v:
                print(f"Value changed from {P[i, idx]} to {v}")
            P[i, idx] = v

def crossover(P):
    pass

P = geneneration(10)
target =  np.array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1])
f = fitness(P[0], target)
selection(P, target)
print(P)
mutation(P, 10, 0.05)
print(P)

[6 8 6 3 9 4 7 8 5 6]
[[0 1 0 0 1 1 1 1 0 1 0 1]
 [0 0 0 0 1 1 0 1 0 1 1 0]
 [1 0 1 1 1 0 0 0 1 0 1 1]
 [1 1 1 0 0 1 1 1 0 1 0 1]
 [0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 1 1 1 0 1 0 1]
 [1 1 0 0 1 0 0 1 0 1 0 1]
 [1 1 0 0 1 0 0 1 1 0 1 1]
 [1 1 0 1 0 1 1 0 1 0 0 0]
 [0 1 1 0 0 1 0 1 0 1 0 0]]
Value changed from 1 to 0
[[0 1 0 0 1 1 1 1 0 1 0 1]
 [0 0 0 0 1 1 0 1 0 1 1 0]
 [1 0 1 1 1 0 0 0 1 0 1 1]
 [1 1 1 0 0 1 1 1 0 1 0 1]
 [0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 1 1 1 0 1 0 1]
 [1 1 0 0 1 0 0 1 0 1 0 1]
 [1 1 0 0 1 0 0 1 1 0 1 1]
 [0 1 0 1 0 1 1 0 1 0 0 0]
 [0 1 1 0 0 1 0 1 0 1 0 0]]
